name: Shared Workflow

on:
  workflow_call:
    inputs:
      message:
        description: 'Message to display'
        required: true
        type: string

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Print the message
      run: echo "${{ inputs.message }}"